# Logo
logo_image_source: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/assets/anodyne.svg

# Index Page
index_banner_text: Kaluo
index_banner_text_secondary: Welcome to Kaluo's blog
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  # About: /about.html
  # Contact: /contact.html
  About: /about
  Contact: /contact

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: https://avatars2.githubusercontent.com/u/27357116?s=400&u=d547847f75e76eee6e4790fbfc8a3a3dc845d03a&v=4
about_widget_text: "Welcome to Kaluo's blog"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/?lang=en
    fa_icon: fa-twitter
  - url: https://www.facebook.com/
    fa_icon: fa-facebook
  - url: https://dribbble.com/
    fa_icon: fa-dribbble 
  - url: https://github.com/klugjo/hexo-theme-anodyne
    fa_icon: fa-github
  - url: https://plus.google.com/
    fa_icon: fa-google-plus
  - url: https://www.behance.net/
    fa_icon: fa-behance
  - url: https://500px.com/
    fa_icon: fa-500px
  - url: mailto:test@example.com
    fa_icon: fa-envelope
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: "@Untitled. All right reserved | Design & Hexo <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
